### ISSUE TITLE
Getting this error when running jekyll serve

### ISSUE THREAD

**Issue by zerocase** [aerobless/jekyll-photo-gallery#10]
```
Configuration file: /home/zerocase/jekyll-photo-gallery/sample-installation/_config.yml
            Source: /home/zerocase/jekyll-photo-gallery/sample-installation
       Destination: /home/zerocase/jekyll-photo-gallery/sample-installation/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
        30: from /home/zerocase/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
        29: from /home/zerocase/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
        28: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        27: from /home/zerocase/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        26: from /home/zerocase/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        25: from /home/zerocase/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        24: from /home/zerocase/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        23: from /home/zerocase/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        22: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        21: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        20: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        19: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        18: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
        17: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
        16: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
        15: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:81:in `process'
        14: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:217:in `cleanup'
        13: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:15:in `cleanup!'
        12: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:25:in `obsolete_files'
        11: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:59:in `new_files'
        10: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:59:in `tap'
         9: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:60:in `block in new_files'
         8: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:348:in `each_site_file'
         7: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:348:in `each'
         6: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:349:in `block in each_site_file'
         5: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:349:in `each'
         4: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:350:in `block (2 levels) in each_site_file'
         3: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/cleaner.rb:60:in `block (2 levels) in new_files'
         2: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/static_file.rb:59:in `destination'
         1: from /home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/static_file.rb:166:in `url'
/home/zerocase/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/static_file.rb:153:in `cleaned_relative_path': undefined method `length' for nil:NilClass (NoMethodError)
```

**Comment by techaware** [comment]
I am also facing the same issue. Do you have any resolution?
